version: '3'

services:
  dubai-cycling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dubai-cycling-explorer
    ports:
      - "7868:7868"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
